---
 - name: Generate self-signed SSL certificate
   command: openssl req -new -nodes -x509 -subj '{{ssl_certs_fields}}' -days {{ssl_certs_days}} -keyout {{ssl_certs_privkey_path}} -out {{ssl_certs_cert_path}} -extensions v3_ca creates={{ssl_certs_cert_path}}
